### ISSUE TITLE
Feeding playlist to youtube-dl yields only 1 track

### ISSUE THREAD

**Issue by DeForce** [TeaSpeak/TeaMusic#12]
Giving bot command:
.mbot yt https://www.youtube.com/playlist?list=PLQAuJ2UwHIbGWvN5WdOU87KMkZamGaJeu

It only queues one track:
Title       : 3 HOURS of The Best Relax Music | SUPERNOVA | for Mind Opening, DEEP Meditation, Yoga

Queue size  : 0

**Comment by WolverinDEV** [comment]
Yeah play lists dosnt work yet :)

**Comment by WolverinDEV** [comment]
implemented within the next release

**Comment by DeForce** [comment]
Is it possible to randomize the playlist?

**Comment by WolverinDEV** [comment]
when you set the replay mode to shuffle yes :)
