### ISSUE TITLE
Time of activity

### ISSUE THREAD

**Issue by Chazotu** [TeaSpeak/TeaMusic#6]
Another thing to add as an improvement would be the time of activity of the musicbot.
Currently the "online since" does not take into account that the server has been restarted. I think the best solution would be this:

```
//
// int musicbotCreationTime is the result in seconds of time since creation
// (example: 10 days = 864000 seconds)
// int serverUptime is the server uptime in seconds
//

unsigned int getMusicbotUptime ( unsigned int musicbotCreationTime, unsigned int serverUptime ) { 
   if ( musicbotCreationTime > serverUptime )  {
      return serverUptime;
   }
   return musicbotCreationTime;
}
```

If the server is restarted, the musicbotCreationTime will always be greater than serverUptime and in this case the uptime of the musicbot must be equal to the server's uptime. Otherwise, the function returns the calculation that is done in the actual version of teaspeak server that is all the time elapsed since the creation of the bot.

- An Config Option to choose if the Bots Online Time is the total online time or the Uptime of the Server

**Comment by WolverinDEV** [comment]
Implemented:
Each bot has a property called `client_uptime_mode`.
0 = TIME_SINCE_CREATED
1 = TIME_SINCE_LOADED
