### ISSUE TITLE
Write on song change

### ISSUE THREAD

**Issue by Chazotu** [TeaSpeak/TeaMusic#8]
Make the musicbot write on song change the currently reproduced song in the channel (with on/off switch... Not everybody want to hear PLINT every song change)

Example:
`<66:66:66> "NiceBot": Now playing: How to break wolverindev balls feat. redfox and co.`

And maybe even change the description of the bot with the name of the song played so when a person enters the channel can see the name of the song quickly.

**Comment by WolverinDEV** [comment]
implemented within the next version.
